class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
We found a lot of errors in Kyverno logs that someone tries to Update namespaces after creation.
With the help of Kyverno verbosity level 6 we found out it's OpenShift itself.
Builds up on #8 
=> Allow OpenShift to bypass Namespace policies

class/appuio-cloud.yml, class/defaults.yml, component/common.libsonnet, component/generated-rolebindings.jsonnet, component/namespace-policies.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
* Adds a Kyverno Rule to generate the admin Rolebinding when creating new namespaces for an organization.
=> Add generator rule to create rolebinding in new namespaces

component/namespace-policies.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
This PR adds a mutating policy which sets a namespace's `appuio.io/organization` label to the user's default organization (sourced from annotation `appuio.io/default-organization` on the User object) if the namespace which is being created doesn't have the label.
This is implemented in the same cluster policy as the label checking, which works as expected, as mutations are executed before
validations.
Currently the annotations on User objects providing the information about default organizations is generated semi-manually by a Go program which extracts the user's default organization from Keycloak and writes it to the User object.
=> Inject user's default organization when creating namespace without the organization label

class/appuio-cloud.yml, component/namespace-policies.jsonnet, component/project-template.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/20_project_template.yaml
This PR configures a custom OCP project template which only creates a `Project` resource and no rolebindings.
The PR also adds a mutate policy which adds the requesting user's default organization to the project based on the value of annotation
`openshift.io/requester` on the Project resource created by the OCP project template.
Additionally, we refactor the code a bit since this new mutate policy is mostly identical to the one which handles setting a default organization when users create projects with `kubectl create ns`.
=> Create OCP project template and add organization label to projects

component/namespace-policies.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
Kyverno provides the requesting user's groups in `request.userInfo.groups`.
This commit changes the `is-in-organization` policy to use this variable instead of fetching all groups from the Kubernetes API when validating that the user is part of the organization specified on the Namespace object.
=> Use `request.userInfo.groups` to validate the organization label

component/common.libsonnet, component/generated-rolebindings.jsonnet, component/namespace-policies.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
According to https://kyverno.io/docs/writing-policies/match-exclude/ Kyverno is planning to deprecate configurations which specify resource filters directly under keys `match` or `exclude` and recommends to use either key `all` or `any` under those keys.
Each clause can have exactly one of `all` or `any`.
This commit restructures all our policies to use subkey `all` under `match`. We currently don't nest the cluster roles to exclude under a subkey as there's an open bug that matching of cluster roles doesn't work if they're nested under `all` or `any`, cf https://github.com/kyverno/kyverno/issues/2301.
=> Use recommended syntax for Kyverno match and exclude configurations

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
> Looking at the current usage, around two thirds of the namespaces use 4GiB or less memory.
> This sounds like a reasonable quota to start with.
> For the compute resources, let's assume a node size of 32GB memory with 8 CPU cores (Plus-32 on Cloudscale and Huge on Exoscale).
> This results in 8 namespaces per node and therefore we can restrict the CPU requests to 1 core and the CPU limit to 1.5 cores.
=> Update CPU/Mem resource quotas

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
See https://kb.vshn.ch/appuio-cloud/references/quality-requirements/performance/resource-quota.html
(27.9.2021)
Or: https://github.com/appuio/appuio-io-docs/blob/2e11cb7729bc157e70778ced4e1ff52515d0504e/docs/modules/ROOT/pages/references/quality-requirements/performance/resource-quota.adoc
=> Introduce ephemeral-storage quotas

class/appuio-cloud.yml, class/defaults.yml, component/build-strategy.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/15_disallow_docker_build_strategy_patch.yaml
This PR disallows the OpenShift Docker build strategy.
```sh 
❯ kubectl apply -f- << YAML 
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
name: docker-buildconfig
spec:
strategy:
dockerStrategy: {}
source:
dockerfile: "FROM alpine\nRUN apk add curl"
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
name: source-buildconfig
spec:
strategy:
jenkinsPipelineStrategy: {}
source:
git:
uri: https://github.com/appuio/component-appuio-cloud.git
YAML
buildconfig.build.openshift.io/source-buildconfig created
Error from server (Forbidden): error when creating "STDIN": buildconfigs.build.openshift.io "docker-buildconfig" is forbidden: build strategy Docker is not allowed
```
as they show up in the …
=> Disallow docker build strategy

class/defaults.yml, component/quota-limitrange.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
The quotas `organization-compute` and `organization-compute-terminating` apply for non-terminating pods (pods where `.spec.activeDeadlineSeconds` is `nil`) and terminating pods (pods with `.spec.activeDeadlineSeconds` >= 0) respectively.
The `Terminating` and `NotTerminating` scopes restrict quotas to the following resources:
* `pods`
* `cpu`
* `memory`
* `requests.cpu`
* `requests.memory`
* `limits.cpu`
* `limits.memory`
Therefore we need to create a separate quota `organization-objects` for the remaining object quotas which we care about.
=> Split resource quotas into `objects`, `compute` and `compute-terminating`

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
Fix for #30 which uses the same values as APPUiO Public for the terminating compute quota.
=> Use same values as on APPUiO Public for terminating compute quota

class/appuio-cloud.yml, class/defaults.yml, component/runonce-activedeadlineseconds.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/30_set_runonce_activedeadlineseconds.yaml
Create a new cluster policy which ensures that `.spec.activeDeadlineSeconds` is set on all "runonce" pods (pods with `.spec.restartPolicy` set to "OnFailure" or "Never").
This policy doesn't modify "runonce" pods which already have `.spec.activeDeadlineSeconds` set.
All other "runonce" pods are configured with the global default activeDeadlineSeconds value extracted from component parameter `runOnceActiveDeadlineSeconds.defaultActiveDeadlineSeconds`.
Users can override the default value on individual namespaces by setting annotation with key `runOnceActiveDeadlineSeconds.overrideAnnotationKey` to the desired default value for pods in that namespace.
=> Add a clusterpolicy to set default for `.spec.activeDeadlineSeconds`

class/defaults.yml, component/generated-rolebindings.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
To allow users to transfer a namespace we need to allow them to edit it.
The existing policies will check that the user is part of the target organization.
I'm not really happy with the naming. I'm open for suggestions
=> Enable namespace transfer

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/00_namespace.yaml
This component isn't really part of Project Syn, just managed by it.
Therefore it should belong to its own namespace prefix 'appuio'
NOTE: At this moment, this component doesn't deploy any namespace-scoped resources, so it shouldn't break anything.
Also, it better aligns with Keycloak IdP, which is installed in `appuio-keycloak`
=> Change default namespace

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
If using mutate, Kyverno appends an annotation to debug the mutate patches.
The annotation is appended in the context of the original requestor.
Thus we have to whitelist the annotation or the later validation rejects the request.
This should be safe because:
- The annotation is only for debugging and not referenced elsewhere.
- The mutating policies are validated with a validation rule too.
=> Ignore Kyverno mutate debug annotation

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
Cilium is installed in the namespace `cilium`. Now that we opted to make use of it, we need to protect that namespace from end user interference.
=> Add Cilium to the list of reserved namespaces

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
Allows to edit 
* `network-policies.syn.tools/no-defaults`
* `network-policies.syn.tools/purge-defaults`
=> Allow network policy labels to be edited by users

component/generated-rolebindings.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml
By adding the permission to delete namespaces with a `RoleBinding` we only allow a user to delete the `Namespace` that contains the `RoleBinding`.
=> Allow user to delete namespaces he owns

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
The default CPU limit was way too low, even for a simple application with a few Pods.
=> Raise default CPU requests and limits for NotTerminating resources

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
See product `flexible:v6` in https://control.vshn.net/appuio/products/appuio%20public (internal) for the current terminating quota for new projects on APPUiO Public.
=> Update default terminating quota to match APPUiO Public

class/defaults.yml, component/common.libsonnet, component/generated-rolebindings.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/20_project_template.yaml, tests/kyverno/defaults/generate-default-rolebinding-in-ns-test.yaml, tests/kyverno/defaults/generate-default-rolebinding-in-ns-variables.yaml, tests/kyverno/defaults/generate-default-rolebinding-in-ns/init-rolebinding.yaml, tests/kyverno/defaults/generate-default-rolebinding-in-ns/uninit-rolebinding-patched.yaml, tests/kyverno/defaults/generate-default-rolebinding-in-ns/uninit-rolebinding.yaml
We do this by add a label to the `admin` rolebinding created by the
project template and modifying it through a mutating policy.
=> Unify default RoleBinding of namespaces and projects

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
It turns out that Kyverno doesn't support wildcards for specifying excluded or matching cluster roles for policies.
As a short term workaround, we replace the wildcard cluster role with a list of all the clusterroles the wildcard would expand to on APPUiO Cloud.
=> Don't use wildcard in excluded cluster roles for Kyverno policies

component/namespace-policies.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/01_appuio_ns_provisioners_crb.yaml
We actually need to allow service accounts to create namespaces. Otherwise https://github.com/appuio/component-appuio-cloud/pull/55 is fairly useless.
Any service account should be in group `system:serviceaccounts` according to https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens
=> Allow Service Accounts to create namespaces

class/defaults.yml, component/generated-rolebindings.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/10_generate_default_rolebinding_in_ns.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/10_namespace_editor_clusterrole.yaml
Create a single cluster role `namespace-owner` instead of creating a role `namespace-owner` in each organization namespace and create a role binding called `namespace-owner` granting the clusterrole to the namespace's organization's group.
=> Change namespace-owner config to use a ClusterRole

class/defaults.yml, component/runonce-activedeadlineseconds.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/30_set_runonce_activedeadlineseconds.yaml, tests/kyverno/defaults/set-runonce-activedeadlineseconds-test.yaml, tests/kyverno/defaults/set-runonce-activedeadlineseconds-variables.yaml, tests/kyverno/defaults/set-runonce-activedeadlineseconds/cm-http01-pod.yaml, tests/kyverno/defaults/set-runonce-activedeadlineseconds/eligible-pod-deadlineseconds.yaml, tests/kyverno/defaults/set-runonce-activedeadlineseconds/eligible-pod.yaml, tests/kyverno/defaults/set-runonce-activedeadlineseconds/existing-deadline-pod.yaml, tests/kyverno/defaults/set-runonce-activedeadlineseconds/managed-pod.yaml
This PR introduces support for not adding `activeDeadlineSeconds` to "run-once" pods based on their labels.
This can be useful to exclude some pods (e.g. cert-manager http01 solver pods) from the default deadline logic.
=> Add support to skip adding `activeDeadlineSeconds` to "run-once" pods based on their labels

docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_projects.adoc, docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc, docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc, docs/modules/ROOT/pages/references/policies/10_generate_default_rolebinding_in_ns.adoc, docs/modules/ROOT/pages/references/policies/11_generate_quota_limit_range_in_ns.adoc, docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc, docs/modules/ROOT/pages/references/policies/30_set_runonce_activedeadlineseconds.adoc, tools/render/render.go, tools/render/templates/policy.adoc
The policy renderer doesn't actually check what the policy does to determine if it's a "mutate", "generate", or "validate" policy, it just does a string match on the policy YAML for each of those words and returns the first one it finds as the policy type.
Previously the code searched "generate", "mutate", "validate" without any fencing.  Since our excludes contain the string "validate" a lot of policies were mislabeled.
This commit changes the implementation to instead go through the rules on the parsed `kyvernov1.ClusterPolicy` object and identify all rule types present in the policy.
Follow-up for #62 
=> Kyverno policy renderer: extract policy types from parsed policies

component/common.libsonnet, component/namespace-policies.jsonnet, docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
Previously, users could create namespaces matching a disallowed pattern with `oc new-project`.
Discovered while writing the documentation for #63 
=> Deny `ProjectRequests` which match a disallowed name pattern

class/defaults.yml, docs/modules/ROOT/pages/references/policies/11_generate_quota_limit_range_in_ns.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
The component uses a default memory-per-core ratio of 4Gi. This commit adjusts the default limitrange requests to match that ratio.
Note that 25m / 100Mi doesn't exactly match the 4Gi/core ratio, even though the values appear to have a ratio of 1:4.
Instead of adjusting the memory requests to 102.4Mi to match the default ratio exactly, we go with 10m / 100Mi for the default requests.
This should be a good default, since most applications really don't need a lot of CPU when they're idle, and we leave the default limit at 600m / 768 Mi, so standard bursty workloads which don't have to serve hundreds of queries per second should be completely fine with the new default requests.
=> Adjust default limitrange requests ratio

class/defaults.yml, docs/modules/ROOT/pages/references/policies/11_generate_quota_limit_range_in_ns.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
We want to have fairly strict quotas for storageclasses backed by Rook-Ceph. This ensures that a single new PVC can't fill up the Ceph cluster to the point where it goes into read-only mode to protect itself from becoming so full that it can't be rebalanced anymore.
=> Add storage quotas for Rook-Ceph-backed storageclasses

component/quota-limitrange.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, docs/modules/ROOT/pages/references/policies/11_generate_quota_limit_range_in_ns.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
The storageclass-specific quotas use keys which are too long to work with the generic annotation-based system for customizing the quotas in single namespaces.
This PR introduces a special annotation `resourcequota.appuio.io/<quota-name>.storageclasses` whose value is parsed as a JSON object. If there's a key which matches an existing `<storageclass>.storageclass.k8s.io` quota, the policy will use the value of that key as the final value for that quota instead of the default defined in the component defaults.
=> Add support for overriding storageclass-specific quotas

component/main.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/00_namespace.yaml
We deactivate the default network policies in the APPUiO Cloud agent namespace in order to ensure that various aggregated API servers (e.g. `openshift-apiserver`) can connect to the validating webhook served by the agent.
=> Deactivate default network policies in the agent namespace

class/defaults.yml, docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc, docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc, docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
Adjust resource-locker clusterrole names to match the new names generated by component resource-locker v2.5.0+.
Note that the new names are stable across clusters but may change when we change the actual ResourceLocker configuration they belong to.
See also https://github.com/projectsyn/component-resource-locker/pull/51
=> Update ResourceLocker cluster roles which are exempt from policies

class/defaults.yml, docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc, docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc, docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
By matching the clusterrole there is the potential of privilege escalation as users genrally have enough permission to give themselves the resource locker clusterrole for their own namespace.
This issue doesn't immediately exit for the other clusterroles as they all provide higher permissions than the user itself has.
=> Switch to subject instead of clusterrole for resource locker

component/build-strategy.jsonnet, tests/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/15_disallow_docker_build_strategy_patch.yaml
To overwrite the `rbac.authorization.kubernetes.io/autoupdate` annotation we need to patch `metadata.annotations`, not `annotations`.
The fixed patch also needs https://github.com/projectsyn/component-resource-locker/pull/63, otherwise it won't apply on the cluster.
=> Fix patch for disallowing docker builds

tools/render/git.go
A bit hacky but this should now allow to run the policy doc generate tool if you cloned the repo using the SSH URL.
=> Add support for SSH URL to the policy doc generator

class/defaults.yml, component/agent.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
Also set default memory limit to 1Gi (up from 256Mi), since we've seen the new agent pods which also observe namespaces crashlooping on zones which have more than a handful of namespaces.
Follow-up for #129 
=> Make APPUiO Cloud Agent resource requests and limits configurable

component/common.libsonnet, component/namespace-policies.jsonnet, component/namespace-quota.jsonnet, component/project-policies.jsonnet, docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_projects.adoc, docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc, docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc, docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_projects.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
Kyverno v1.8.0  https://github.com/projectsyn/component-kyverno/pull/61 introduces multiple breaking changes. Most importantly missing fields now evaluate to `null` instead of `""`, and exclude now needs to use the `any` keyword to be able to match a clusterrole or a subject (and not both)
=> Update kyverno policies to work with version 1.8.0

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/10_additional_clusterroles.yaml
This clusterrole can be used to delegate access to the user-workload monitoring metrics. By binding this clusterrole in a namespace it gives the subjects access to all metrics in that namespace
=> Add clusterrole appuio:metrics-viewer

class/defaults.yml, docs/modules/ROOT/pages/references/policies/11_generate_quota_limit_range_in_ns.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml
We've observed that large amounts of completed jobs (and associated pods) can cause increased resource consumption in control plane components (e.g. apiserver memory usage). We've also observed noticeable `kubectl` lag for operations like `kubectl get pods -A`.
We've picked an initial limit of 150 jobs which should be sufficient for regular uses (e.g. appuio-cloud-reporting currently has 57 jobs in the namespace).
=> Add `count/jobs.batch` quota of 150 to `organization-objects` resourcequota

class/defaults.yml, docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc, docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc, docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
On OpenShift 4.11 the `podsecurity-admission-label-syncer-controller` needs to modify namespace labels to ensure the namespace's PSA labels match the most privileged SCC that can be used in the namespace, cf. https://docs.appuio.cloud/user/explanation/pod-security-admissions.html
=> Add PSA namespace label syncer clusterrole to bypass clusterroles

class/defaults.yml, docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc, docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc, docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc, docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml
OLM operator seems to be desparate to update the namespaces: https://github.com/appuio/component-appuio-cloud/issues/76#issuecomment-1335185729
=> Allow OLM operator to bypass NS restrictions

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_default_org_role_binding.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/10_additional_clusterroles.yaml
This PR adds role bindings for the `monitoring-edit` and `alert-routing-edit` cluster roles to the default role bindings created in each organization namespace.
Additionally, the PR adds a cluster role `monitoring-edit-probe`, and an associated default role binding. This additional cluster role is necessary because the upstream `monitoring-edit` cluster role doesn't grant edit permissions for the `Probe` custom resource.
changelog.
=> Configure access to user workload monitoring in the component defaults

CODEOWNERS, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_webhook_cert_secret.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_projects.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/15_disallow_docker_build_strategy_patch.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/30_set_runonce_activedeadlineseconds.yaml
changelog.
- [-] Update the documentation.
- [-] Link this PR to related issues or PRs.
=> Switch CodeOwners to Aldebaran Tech

class/defaults.yml, component/agent.jsonnet, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
=> Support scheduling Cloud Agent on master nodes

component/agent.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
=> Allow removing appuio-cloud-agent config entries by setting them to `null`

component/agent.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml
This lead to the agent not receiving new namepaces.
changelog.
=> Don't inject `namespaceSelector` for namespace and project validating webhooks

component/main.jsonnet, tests/golden/defaults/appuio-cloud/appuio-cloud/01_appuio_ns_provisioner_role.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_appuio_ns_provisioners_crb.yaml
This was removed by accident in #207.
changelog.
=> Re-add namespace self provisioning

class/defaults.yml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_default_org_role_binding.yaml, tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
The same permissions are part of the `admin` cluster role, so we don't need to setup an explicit organization role binding for the `cluster-logging-application-view` cluster role.
Reverts #216 
changelog.
=> Remove unnecessary organization role binding `cluster-logging-application-view`
