component/namespace-policies.jsonnet
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml

@ccremer FYI we forgot one exclude in the `organisation namespace` rule.

Fix rule: Add common ns bypass excludes

---

class/defaults.yml
hack/find-clusterroles.sh
tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml

Found roles with the `hack/find-clusterroles.sh` script.

Exempt all (system) clusterroles allowed to edit namespaces from restrictions

---

class/appuio-cloud.yml
component/common.libsonnet
component/project-policies.jsonnet
tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml

Add policy to deny Project creation if requesting user has no default organization

---

class/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml

To be consistent on the units.

Use Gi in Memory Max LimitRange instead of G

---

component/quota-limitrange.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml

Add option to override resource-quota defaults per namespace

---

.gitignore
.sync.yml
Makefile
Makefile.kyverno.mk
class/defaults.yml
component/common.libsonnet
component/namespace-policies.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
tests/kyverno/defaults/validate-namespace-metadata-test.yaml
tests/kyverno/defaults/validate-namespace-metadata-variables.yaml
tests/kyverno/defaults/validate-namespace-metadata/auxiliary-annotation.yaml
tests/kyverno/defaults/validate-namespace-metadata/auxiliary-label.yaml
tests/kyverno/defaults/validate-namespace-metadata/delete-existing-auxiliary-annotation.yaml
tests/kyverno/defaults/validate-namespace-metadata/delete-existing-auxiliary-label.yaml
tests/kyverno/defaults/validate-namespace-metadata/ignore-existing-auxiliary-annotation.yaml
tests/kyverno/defaults/validate-namespace-metadata/ignore-existing-auxiliary-label.yaml
tests/kyverno/defaults/validate-namespace-metadata/no-annotations.yaml
tests/kyverno/defaults/validate-namespace-metadata/no-labels.yaml
tests/kyverno/defaults/validate-namespace-metadata/null-annotations.yaml
tests/kyverno/defaults/validate-namespace-metadata/null-labels.yaml
tests/kyverno/defaults/validate-namespace-metadata/update-existing-auxiliary-annotation.yaml
tests/kyverno/defaults/validate-namespace-metadata/update-existing-auxiliary-label.yaml
tests/kyverno/defaults/validate-namespace-metadata/whitelisted-and-auxiliary-annotations.yaml
tests/kyverno/defaults/validate-namespace-metadata/whitelisted-and-auxiliary-labels.yaml
tests/kyverno/defaults/validate-namespace-metadata/whitelisted-annotation.yaml
tests/kyverno/defaults/validate-namespace-metadata/whitelisted-label.yaml

This PR adds validation rules for annotations and labels on namespaces. Valid annotations and labels have to be explicitly added to an allowlist.
[`kyverno test`](https://kyverno.io/docs/kyverno-cli/#test) from the Kyverno CLI is used for unit testing the rules.

Namespace label validation rules

---

component/namespace-policies.jsonnet
tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml

Append given labels/annotations to the error message.
A diff is not possible in this context since the foreach recursive replacement trick does not work.
- [ x] Categorize the PR by setting a good title and adding one of the labels:

Make namespace validation easier to debug

---

component/namespace-quota.jsonnet
tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml

Without this precondition, editing or deleting namespaces is also blocked if quota is reached.

Add create precondition to namespace quota policy

---

class/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml

Remove Max Limits per Container and Raise Default CPU and Memory Limits

---

component/namespace-policies.jsonnet
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_projects.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml

Enable Namespace creation through service accounts

---

docs/modules/ROOT/pages/index.adoc

Improve component docs index page

---

class/defaults.yml
docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc
docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc
docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml

Required for https://github.com/appuio/component-openshift4-console/pull/22

Allow openshift4-console ResourceLocker namespace patch to bypass policies

---

class/appuio-cloud.yml
class/defaults.yml
component/agent.jsonnet
component/main.jsonnet
component/monitoring.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc
tests/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/00_namespace.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/20_metrics_service.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/10_monitoring/00_servicemonitor-appuio-cloud-agent.yaml

Add option to scrape APPUiO Cloud Agent metrics

---

class/defaults.yml
docs/modules/ROOT/pages/references/policies/11_generate_quota_limit_range_in_ns.adoc
tests/golden/defaults/appuio-cloud/appuio-cloud/11_generate_quota_limit_range_in_ns.yaml

I ended up creating this PR while I was refining https://ticket.vshn.net/browse/APUB-273.

Match default requests with the platform's ratio

---

class/defaults.yml
component/main.jsonnet
docs/modules/ROOT/pages/references/parameters.adoc

Allow setting metadata on component namespace

---

class/defaults.yml
docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc
docs/modules/ROOT/pages/references/policies/03_projectrequest.adoc
docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/03_projectrequest.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml

Allow the cluster-logging-operator to bypass namespace restrictions

---

.cruft.json
component/build-strategy.jsonnet
tests/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/15_disallow_docker_build_strategy_patch.yaml

Update component to use `patch-operator.libsonnet` directly

---

component/agent.jsonnet

Only install `ZoneUsageProfile` CRD if the agent image tag is >= v0.10.0

---

class/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_role.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml

Update `appuio/appuio-cloud-agent` to `v0.12.1`

---

class/defaults.yml
docs/modules/ROOT/pages/references/policies/02_disallow_reserved_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_organization_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_organization_sa_namespaces.adoc
docs/modules/ROOT/pages/references/policies/02_validate_namespace_metadata.adoc
docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_disallow_reserved_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_organization_sa_namespaces.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/02_validate_namespace_metadata.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml

See https://github.com/appuio/component-appuio-cloud/pull/186
changelog.

Allow Cloudscale CCM to set LB service labels

---

class/appuio-cloud.yml
class/defaults.yml
docs/modules/ROOT/pages/references/parameters.adoc
postprocess/disable-kyveno-policies.jsonnet

Allow to generically disable Kyverno policies

---

class/defaults.yml
docs/modules/ROOT/pages/references/policies/12_namespace_quota_per_zone.adoc
tests/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/12_namespace_quota_per_zone.yaml

Inject legacy namespace quota into agent config

---

class/defaults.yml
component/agent.jsonnet
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/10_webhook_config.yaml

Implement ResourceQuota and LimitRange generation in agent

---

class/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml

This brings the LimitRange minimum CPU and memory requests in line with the fair use ratio (1:4) on cloudscale.
changelog.

Adjust LimitRange minimum CPU request to `1m`

---

class/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_default_org_role_binding.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml

This is required now that we've migrated APPUiO to LokiStack.
changelog.

Grant `cluster-logging-application-view` to organizations

---

class/defaults.yml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/01_config_map.yaml
tests/golden/defaults/appuio-cloud/appuio-cloud/01_agent/02_deployment.yaml

Add OLMv1 meta-operator SA to privileged users list
